# Generated by Django 6.0.4 on 2026-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('genre', models.CharField(choices=[('action', 'Acción'), ('comedy', 'Comedia'), ('drama', 'Drama'), ('horror', 'Terror'), ('scifi', 'Ciencia ficción'), ('animation', 'Animación'), ('thriller', 'Suspenso')], max_length=20, verbose_name='Género')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('release_date', models.DateField(verbose_name='Fecha de estreno')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Calificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-release_date'],
            },
        ),
    ]
